'use client';
import { StyleSheet } from "react-native-web";

export const styles = StyleSheet.create({
  outerContainer:{
    display: 'flex',
    alignItems: 'center',
    flexDirection:'column',
    justifyContent: 'center'
    },
  container: {
    display: 'flex',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  column: {
    display:'flex',
    flexDirection: "column",
    alignContent: 'center',
    justifyContent: 'center',
  },
  row: {
    display:'flex',
    flexDirection: "row",
    alignContent: 'center',
    justifyContent: 'center',
    marginTop: 20
  },
  middleSection: {
    margin: 10,
    width: 'fit-content'
  },
  titleContainer:{
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    width: 'fit-content',
    marginTop: 10
  },
  title:{
    marginTop: 10,
    textShadow: '-2px 2px 4px gray, 2px 2px 2px gray',
    textAlign: 'center'
  },
  subCan: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    alignSelf: 'center',
    marginTop: -150,
    marginLeft: -75,
    width:350
  },
  button: {
    display:'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width:45,
    height:45,   
    color:'#4e4e4e',
    backgroundColor: '#6c6c6c',
    textShadow: '-1px 1px 1px #4e4e4e',
    fontSize: 35,
    borderColor: '#4e4e4e',
    borderWidth: 2,
    borderRadius: 6,
    margin: 5,
    textAlign: 'center',
    paddingBottom: 1,
  },
  hover: {
    display:'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width:45,
    height:45,
    backgroundColor: '#4e4e4e',
    borderColor: '#fff',
    borderWidth: 2,
    borderRadius: 6,
    textShadow: '-1px 1px 1px #ffffff',
    fontSize: 35,
    cursor: 'pointer',
    textAlign: 'center',
    paddingBottom: 1,
    margin: 5,   
    color:'#ffffff',
  },
  submitButton: {
    display:'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width:'fit-content',
    height:45,
    padding:3,
    color:'#4e4e4e',
    backgroundColor: '#6c6c6c',
    textShadow: '-1px 1px 1px #4e4e4e',
    fontSize: 35,
    borderColor: '#4e4e4e',
    borderWidth: 2,
    borderRadius: 6,
    margin: 5,
    textAlign: 'center'
  },
  submitHover: {
    display:'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width:'fit-content',
    height:45,
    padding:3, 
    color:'#ffffff',
    borderColor: '#fff',
    borderWidth: 2,
    borderRadius: 6,
    backgroundColor: '#4e4e4e',
    textShadow: '-1px 1px 1px #ffffff',
    fontSize: 35,
    cursor: 'pointer',
    margin:5,
    textAlign: 'center'
  },
cancelButton: {
    display:'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width:'fit-content',
    height:45,
    padding:3,  
    color:'#681402',
    backgroundColor: '#6c6c6c',
    textShadow: '-1px 1px 1px #681402',
    fontSize: 35,
    borderColor: '#681402',
    borderWidth: 2,
    borderRadius: 6,
    margin:5,
    textAlign: 'center'
  },
  cancelHover: {
    display:'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width:'fit-content',
    height:45,
    padding:3, 
    color:'#fff',
    borderColor: '#fff',
    borderWidth: 2,
    borderRadius: 6,
    backgroundColor: '#681402',
    textShadow: '-1px 1px 1px #fff',
    fontSize: 35,
    cursor: 'pointer',
    margin:5,
    textAlign: 'center'
  },
  defaultSection:{
    width: 150,
    backgroundColor: '#ddd',
    borderColor: '#fdb',
    borderWidth: 3,
    borderRadius: 18,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 22,
    boxShadow: '-2px 2px 8px #9c9c9c',
    margin: 8,
    height: 450,
  }
})